server:
  port: 8081

spring:
  application:
    name: samurai-metadata-aggregation-service
  kafka:
    bootstrap-servers: localhost:29092

kafka:
  topic:
    name: test_topic

metadata-aggregation-service:
  api:
    client:
      id: XXX
      secret: XXX
