server:
  port: 8081

spring:
  application:
    name: samurai-metadata-aggregation-service
  kafka:
    bootstrap-servers: localhost:29092

  datasource:
    url: jdbc:postgresql://localhost:5432/samurai_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  topic:
    name: test_topic

metadata-aggregation-service:
  api:
    client:
      id: ${IGDB_CLIENT_ID}
      secret: ${IGDB_CLIENT_SECRET}
