server:
  port: 8082

spring:
  application:
    name: samurai-metadata-indexer-service
  kafka:
    bootstrap-servers: localhost:29092

metadata-indexer-service:
  opensearch:
    write-index:
      name: "samurai-index"
  kafka:
    topic:
      name: test_topic
    consumer:
      groupId: "test-consumer-group-1"
